Repository openstack-k8s-operators/architecture, pull requests merged in 2024-10, with the labels that each got.

#410 Revert addition of Swift network to va/hci
  dt/pidone/kustomization.yaml
  examples/dt/pidone/nncp/values.yaml
  examples/va/hci/control-plane/nncp/kustomization.yaml
  examples/va/hci/control-plane/nncp/values.yaml
  lib/nncp/ocp_nodes_nncp.yaml
  va/hci/edpm-post-ceph/nodeset/kustomization.yaml
  va/hci/edpm-pre-ceph/nodeset/kustomization.yaml
  va/hci/kustomization.yaml
  va/hci/networking/metallb/kustomization.yaml
  va/hci/networking/metallb/metallb_l2advertisement.yaml
  va/hci/networking/metallb/ocp_ip_pools.yaml
  va/hci/networking/nad/kustomization.yaml
  va/hci/networking/nad/ocp_networks_netattach.yaml
  va/hci/networking/netconfig/kustomization.yaml
  va/hci/nncp/kustomization.yaml
  va/hci/nodeset/kustomization.yaml
Labels: approved, lgtm

#411 Enable Heat for uni04delta-ipv6 DT
  dt/uni04delta-ipv6/control-plane/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
Labels: approved, lgtm, needs-ok-to-test, needs-18.0.0-proposed-cherry-pick

#415 Enable Heat for uni04delta-ipv6 DT
  dt/uni04delta-ipv6/control-plane/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
Labels: approved, lgtm, ok-to-test

#417 Add uni02beta-upstream trigger job
  zuul.d/trigger-jobs.yaml
Labels: approved, lgtm

#338 [BGP_DT01] Enable octavia
  automation/mocks/bgp_dt01.yaml
  dt/bgp/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
  examples/dt/bgp/control-plane/service-values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#392 Introduce DCN DT
  automation/net-env/dcn.yaml
  automation/vars/dcn.yaml
  dt/dcn/README.md
  dt/dcn/edpm-post-ceph/deployment/kustomization.yaml
  dt/dcn/edpm-post-ceph/nodeset/ceph_secret.yaml
  dt/dcn/edpm-post-ceph/nodeset/extra_mounts.yaml
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  dt/dcn/edpm-post-ceph/nodeset/nova_ceph.yaml
  dt/dcn/edpm-pre-ceph/deployment/kustomization.yaml
  dt/dcn/edpm-pre-ceph/nodeset/kustomization.yaml
  dt/dcn/kustomization.yaml
  dt/dcn/namespace.yaml
  examples/dt/dcn/.gitignore
  examples/dt/dcn/README.md
  examples/dt/dcn/control-plane.md
  examples/dt/dcn/control-plane/.gitignore
  examples/dt/dcn/control-plane/kustomization.yaml
  examples/dt/dcn/control-plane/nncp/.gitignore
  examples/dt/dcn/control-plane/nncp/kustomization.yaml
  examples/dt/dcn/control-plane/nncp/values.yaml
  examples/dt/dcn/control-plane/service-values.yaml
  examples/dt/dcn/dataplane-post-ceph.md
  examples/dt/dcn/dataplane-pre-ceph.md
  examples/dt/dcn/deployment/kustomization.yaml
  examples/dt/dcn/deployment/values.yaml
  examples/dt/dcn/edpm-pre-ceph/.gitignore
  examples/dt/dcn/edpm-pre-ceph/deployment/kustomization.yaml
  examples/dt/dcn/edpm-pre-ceph/deployment/values.yaml
  examples/dt/dcn/edpm-pre-ceph/nodeset/kustomization.yaml
  examples/dt/dcn/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/dcn/image.png
  examples/dt/dcn/kustomization.yaml
  examples/dt/dcn/service-values.yaml
  examples/dt/dcn/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#427 Glance DCN: Remove unnecessary configuration and default to az0
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#413 DT - BMO deploy with preprovisioningNetworkData
  .ci/automation-schema.yaml
  automation/mocks/bmo01.yaml
  automation/net-env/bmo01.yaml
  automation/vars/bmo01.yaml
  dt/bmo01/dataplane/baremetalhosts/baremetalhost_template.yaml
  dt/bmo01/dataplane/baremetalhosts/baremetalhosts.yaml
  dt/bmo01/dataplane/baremetalhosts/kustomization.yaml
  dt/bmo01/dataplane/kustomization.yaml
  dt/bmo01/dataplane/nodesets/kustomization.yaml
  dt/bmo01/dataplane/nodesets/network-data-secrets.yaml
  dt/bmo01/dataplane/nodesets/openstackdataplanenodesets.yaml
  dt/bmo01/dataplane/secrets/dataplane-ssh-secret.yaml
  dt/bmo01/dataplane/secrets/kustomization.yaml
  dt/bmo01/dataplane/secrets/nova-migration-ssh-secret.yaml
  dt/bmo01/kustomization.yaml
  dt/bmo01/netconfig/kustomization.yaml
  dt/bmo01/netconfig/netconfig.yaml
  dt/bmo01/nncp/kustomization.yaml
  examples/dt/bmo01/README.md
  examples/dt/bmo01/control-plane.md
  examples/dt/bmo01/control-plane/kustomization.yaml
  examples/dt/bmo01/control-plane/nncp/kustomization.yaml
  examples/dt/bmo01/control-plane/nncp/values.yaml
  examples/dt/bmo01/control-plane/service-values.yaml
  examples/dt/bmo01/data-plane.md
  examples/dt/bmo01/dataplane/baremetalhosts/bmc-secret.env
  examples/dt/bmo01/dataplane/baremetalhosts/kustomization.yaml
  examples/dt/bmo01/dataplane/baremetalhosts/values.yaml
  examples/dt/bmo01/dataplane/kustomization.yaml
  examples/dt/bmo01/dataplane/nodesets/kustomization.yaml
  examples/dt/bmo01/dataplane/nodesets/values.yaml
  examples/dt/bmo01/dataplane/secrets/kustomization.yaml
  examples/dt/bmo01/dataplane/secrets/values.yaml
  examples/dt/bmo01/dataplane/values.yaml
  examples/dt/bmo01/osp-k8s-spine-leaf.svg
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#420 [POC] Add an adoption VA to setup networking
  automation/vars/hci-adoption.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#408 NFV adoption patch
  automation/vars/nfv-ovs-dpdk-sriov-adoption.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm
