Repository openstack-k8s-operators/architecture, pull requests merged in 2024-06, with the labels that each got.

#261 Disabling octavia
  examples/dt/uni01alpha/control-plane/service-values.yaml
Labels: approved, lgtm

#260 Revert "[BGP_DT01] Split EDPM deployment into Networkers and Compute deployments"
  automation/vars/bgp.yaml
  examples/dt/bgp/bgp_dt01/README.md
  examples/dt/bgp/bgp_dt01/data-plane.md
  examples/dt/bgp/bgp_dt01/edpm/computes-deployment/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/deployment/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/deployment/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers-deployment/kustomization.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#259 allow enabling igmp snooping
  examples/va/nfv/ovs-dpdk-sriov/edpm/nodeset/values.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/kustomization.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/neutron_igmp.yaml
Labels: approved, lgtm, ok-to-test

#263 Remove unused params from pidone OSDPNS examples
  examples/va/pidone/edpm/nodeset/values.yaml
  examples/va/pidone/values.yaml
Labels: approved, lgtm

#238 [manila] Adjust service replica counts
  examples/dt/uni02beta/control-plane/service-values.yaml
  examples/va/hci/service-values.yaml
  va/hci/edpm-post-ceph/nodeset/kustomization.yaml
Labels: deployment-topology, validated-architecture, ready-merge, approved, lgtm

#265 Increasing nncp timeout to 3m
  automation/vars/uni01alpha.yaml
  automation/vars/uni02beta.yaml
  automation/vars/uni05epsilon.yaml
  automation/vars/uni06zeta.yaml
Labels: approved, lgtm

#266 Set mysql_wsrep_sync_wait for Glance and global debug option
  examples/dt/bgp/control-plane/service-values.yaml
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
Labels: approved, lgtm

#268 Do not use galera multi-master capability
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#269 change dir name for config
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/neutron_igmp.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/nova_ovs_dpdk_sriov.yaml
Labels: approved, lgtm, needs-ok-to-test, do-not-merge/hold

#264 [BGP_DT01] Fixes in neutron and NAD
  dt/bgp/kustomization.yaml
  dt/bgp/networking/nad/kustomization.yaml
  dt/bgp/networking/nad/ocp_network_template.yaml
  dt/bgp/networking/nad/ocp_networks_netattach.yaml
  examples/dt/bgp/bgp_dt01/control-plane/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/nncp/values.yaml
  examples/dt/bgp/bgp_dt01/control-plane/ocp_networks_netattach.yaml
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
Labels: approved, lgtm

#273 Change Galera PVC request from 500M to 5G
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#270 Disable multipath in Nova for uni05epsilon
  dt/uni05epsilon/edpm/nodeset/kustomization.yaml
  dt/uni05epsilon/edpm/nodeset/nova_custom.yaml
  examples/dt/uni05epsilon/values.yaml
Labels: approved, lgtm

#275 Set HAProxy timeout to 60 seconds for storage
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#252 Add edpmServiceType to nova-custom-sriov srv
  va/nfv/ovs-dpdk/edpm/nodeset/nova_ovs_dpdk.yaml
  va/nfv/sriov/edpm/nodeset/nova_sriov.yaml
Labels: approved, lgtm

#278 Glance is missing extraMounts on uni02beta
  dt/uni02beta/kustomization.yaml
Labels: approved, lgtm

#277 Move manila config in uni04delta DT
  dt/uni04delta/edpm/nodeset/kustomization.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
Labels: do-not-merge

#274 Remove mariadb from OpenStackControlPlane
  lib/control-plane/openstackcontrolplane.yaml
Labels: ready-merge, approved, lgtm

#280 Change tlsCert to tlsCerts
  dt/bgp/edpm/nodeset/nova_custom.yaml
  va/hci/edpm-post-ceph/nodeset/nova_ceph.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/neutron_igmp.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/nova_ovs_dpdk_sriov.yaml
  va/nfv/ovs-dpdk/edpm/nodeset/nova_ovs_dpdk.yaml
  va/nfv/sriov/edpm/nodeset/nova_sriov.yaml
Labels: ↟ priority-high, approved, lgtm

#181 LACP, balance-tcp and IGMP configs changes
  examples/va/nfv/ovs-dpdk-sriov/edpm/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-sriov/service-values.yaml
Labels: enhancement, needs-testing, needs-info, approved, lgtm

#283 Config uni06zeta glance with Cinder
  examples/dt/uni06zeta/control-plane/service-values.yaml
Labels: approved, lgtm

#282 Enable ceph-nfs for uni04delta
  examples/dt/uni04delta/control-plane/service-values.yaml
Labels: approved, lgtm, do-not-merge/hold

#284 Remove NFS from manila protocols list for HCI
  examples/va/hci/service-values.yaml
Labels: ready-merge, approved, lgtm

#240 [manila] Fix "enabled_share_protocols" configuration
  examples/dt/uni02beta/control-plane/service-values.yaml
Labels: bugfix, needs-testing, triaged, approved, lgtm

#257 Use uni* specific Net Env Def in CI
  automation/mocks/bgp.yaml
  automation/mocks/pidone.yaml
  automation/net-env/bgp.yaml
  automation/net-env/pidone.yaml
  automation/net-env/uni01alpha.yaml
  automation/net-env/uni02beta.yaml
  automation/net-env/uni04delta.yaml
  automation/net-env/uni05epsilon.yaml
  automation/net-env/uni06zeta.yaml
  create-zuul-jobs.py
  zuul.d/validations.yaml
Labels: needs-testing, approved, lgtm

#285 [BGP_DT01] Enable IGMP Snooping
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#152 uni07eta dt - deploys networking nodes and Cinder (iSCSI)
  automation/net-env/uni07eta.yaml
  automation/vars/uni07eta.yaml
  dt/uni07eta/README.md
  dt/uni07eta/cinder-volume-ontap-secrets.yaml
  dt/uni07eta/edpm/kustomization.yaml
  dt/uni07eta/edpm/nodeset/kustomization.yaml
  dt/uni07eta/kustomization.yaml
  dt/uni07eta/namespace.yaml
  dt/uni07eta/networker/kustomization.yaml
  dt/uni07eta/networker/nodeset/kustomization.yaml
  dt/uni07eta/nncp/kustomization.yaml
  dt/uni07eta/ocp-networks-octavia-netattach.yaml
  examples/dt/uni07eta/README.md
  examples/dt/uni07eta/control-plane.md
  examples/dt/uni07eta/control-plane/kustomization.yaml
  examples/dt/uni07eta/control-plane/nncp/kustomization.yaml
  examples/dt/uni07eta/control-plane/nncp/values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
  examples/dt/uni07eta/data-plane.md
  examples/dt/uni07eta/edpm/kustomization.yaml
  examples/dt/uni07eta/edpm/values.yaml
  examples/dt/uni07eta/kustomization.yaml
  examples/dt/uni07eta/networker.md
  examples/dt/uni07eta/networker/kustomization.yaml
  examples/dt/uni07eta/networker/nodeset/kustomization.yaml
  examples/dt/uni07eta/networker/nodeset/values.yaml
  examples/dt/uni07eta/networker/values.yaml
  examples/dt/uni07eta/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#287 Update timeouts for uni-jobs
  automation/vars/default.yaml
  automation/vars/uni01alpha.yaml
  automation/vars/uni02beta.yaml
  automation/vars/uni04delta.yaml
  automation/vars/uni05epsilon.yaml
  automation/vars/uni06zeta.yaml
  automation/vars/uni07eta.yaml
Labels: approved, lgtm, needs-ok-to-test

#290 Enable Manila in uni02beta
  dt/uni02beta/kustomization.yaml
Labels: ↟ priority-high, approved, lgtm, ok-to-test

#289 Drop Redis
  dt/uni01alpha/kustomization.yaml
  dt/uni05epsilon/kustomization.yaml
  examples/dt/uni01alpha/README.md
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni05epsilon/README.md
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm, ok-to-test

#288 [uni02beta] Drop NFS from Glance
  dt/uni02beta/kustomization.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
Labels: approved, lgtm, needs-ok-to-test

#281 Add a global flag to enable preserveJobs in all svcs
  automation/vars/default.yaml
  dt/uni05epsilon/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
  examples/dt/bgp/control-plane/service-values.yaml
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
  examples/va/hci/control-plane/kustomization.yaml
  examples/va/hci/control-plane/service-values.yaml
  examples/va/hci/service-values.yaml
  examples/va/nfv/ovs-dpdk-sriov/service-values.yaml
  examples/va/nfv/ovs-dpdk/service-values.yaml
  examples/va/nfv/sriov/service-values.yaml
  examples/va/pidone/service-values.yaml
  lib/control-plane/kustomization.yaml
Labels: ↟ priority-high, approved, lgtm

#291 Apply custom heat config in uni01alpha
  dt/uni01alpha/kustomization.yaml
  examples/dt/uni01alpha/control-plane/service-values.yaml
Labels: approved, lgtm, ok-to-test

#271 Set neutron MTU according to actual value
  examples/dt/uni06zeta/control-plane/service-values.yaml
Labels: needs-info, testing-complete, approved, lgtm, ok-to-test

#296 Use new EDPM 'dataSources' for custom OpenStackDataPlaneServices
  dt/bgp/edpm/nodeset/nova_custom.yaml
  dt/uni04delta/edpm/nodeset/nova_ceph.yaml
  dt/uni05epsilon/edpm/nodeset/nova_custom.yaml
  va/hci/edpm-post-ceph/nodeset/nova_ceph.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/neutron_igmp.yaml
  va/nfv/ovs-dpdk-sriov/edpm/nodeset/nova_ovs_dpdk_sriov.yaml
  va/nfv/sriov/edpm/nodeset/nova_sriov.yaml
Labels: testing, ↟ priority-high, approved, lgtm

#294 Adapt bgp_dt01 to ci-fmw PR1777
  examples/dt/bgp/bgp_dt01/control-plane/nncp/values.yaml
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#295 Re enable ovn_emit_need_to_frag
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#297 Revert "Cinder wait for DB writes on reads"
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#248 added aditional required config for VA2
  examples/va/nfv/ovs-dpdk-sriov/nncp/values.yaml
  examples/va/nfv/ovs-dpdk-sriov/service-values.yaml
  examples/va/nfv/ovs-dpdk/nncp/values.yaml
  examples/va/nfv/ovs-dpdk/service-values.yaml
  examples/va/nfv/sriov/nncp/values.yaml
  examples/va/nfv/sriov/service-values.yaml
  va/nfv/ovs-dpdk-sriov/kustomization.yaml
  va/nfv/ovs-dpdk/kustomization.yaml
  va/nfv/sriov/kustomization.yaml
Labels: bugfix, approved, lgtm, ok-to-test

#276 Use DataPlaneService.DataSources
  va/nfv/ovs-dpdk/edpm/nodeset/nova_ovs_dpdk.yaml
Labels: approved, lgtm

#299 Update glance storageClass propagation
  lib/control-plane/kustomization.yaml
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#300 Revert mysql_wsrep_sync_wait config option
  examples/dt/bgp/control-plane/service-values.yaml
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
Labels: approved, lgtm

#301 Revert "Re enable ovn_emit_need_to_frag"
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#302 Add details about the format of the post Ceph values.yaml
  examples/dt/uni04delta/edpm.md
  examples/va/hci/dataplane-post-ceph.md
Labels: approved, lgtm

#298 alpha + zeta: Fix for node IPs starting from 10
  examples/dt/uni01alpha/control-plane/nncp/values.yaml
  examples/dt/uni06zeta/control-plane/nncp/values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
Labels: approved, lgtm

#293 Glance over cinder (iSCSI) backend
  dt/uni07eta/kustomization.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#304 Add tainted worker to unibeta
  automation/net-env/uni02beta.yaml
  automation/vars/uni02beta.yaml
  examples/dt/uni02beta/control-plane/nncp/kustomization.yaml
  examples/dt/uni02beta/control-plane/nncp/nodes.yaml
  examples/dt/uni02beta/control-plane/nncp/values.yaml
Labels: approved, lgtm

#305 Bump service replicas to 3
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#313 Always set glance replicas to 3
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#314 Set UNI-Beta to replica: 1
  examples/dt/uni02beta/control-plane/service-values.yaml
Labels: approved, lgtm

#306 Unique pod names for cinder and glance
  lib/control-plane/openstackcontrolplane.yaml
Labels: bugfix, approved, lgtm
