Repository openstack-k8s-operators/architecture, pull requests merged in 2024-11, with the labels that each got.

#432 Update Glance edge pod replica count from 3 to 1
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#434 Use bmhLabelSelector in DT bmo01
  examples/dt/bmo01/dataplane/baremetalhosts/values.yaml
  examples/dt/bmo01/dataplane/nodesets/values.yaml
Labels: approved, lgtm

#435 [uni07eta] Bump edpm-deployment wait condition timout
  automation/vars/uni07eta.yaml
Labels: approved, lgtm

#436 DCN Workaround to set Cinder uniquePodNames false
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#441 Document OpenStackControlPlane overwrite pitfall
  docs/contributing/common-pitfalls.md
Labels: approved, lgtm

#439 DCN DT: Add multicells
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  dt/dcn/edpm-post-ceph/nodeset/neutron_metadata.yaml
  examples/dt/dcn/README.md
  examples/dt/dcn/service-values.yaml
  examples/dt/dcn/values.yaml
Labels: approved, lgtm

#445 Edit contents of common-pitfalls document
  docs/contributing/common-pitfalls.md
Labels: approved, lgtm

#440 [DCN] Explicitly set network availability zone parameters
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  examples/dt/dcn/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#418 Enable telemetry in OSASINFRA DT
  dt/osasinfra/edpm-post-ceph/nodeset/kustomization.yaml
  examples/dt/osasinfra/control-plane.md
  examples/dt/osasinfra/service-values.yaml
  examples/dt/osasinfra/values.yaml
Labels: needs-info, approved, lgtm, ok-to-test

#452 Set storage_availability_zone for DCN cinder backup
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#403 Add worker node to run test operator on uni04delta-ipv6 deployments
  .gitignore
  automation/net-env/uni04delta-ipv6.yaml
  dt/uni04delta-ipv6/nncp/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/ocp_worker_nodes.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/values.yaml
Labels: approved, lgtm, needs-ok-to-test

#454 Cherry-pick pull request #403 from gmarcian/add_worker_unidelta_ipv6
  .gitignore
  automation/net-env/uni04delta-ipv6.yaml
  dt/uni04delta-ipv6/nncp/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/ocp_worker_nodes.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/values.yaml
Labels: approved, lgtm, ok-to-test
