Repository openstack-k8s-operators/architecture, pull requests merged in 2024-07, with the labels that each got.

#244 OSASINFRA DT
  automation/vars/osasinfra.yaml
  dt/osasinfra/README.md
  dt/osasinfra/edpm-post-ceph/deployment/kustomization.yaml
  dt/osasinfra/edpm-post-ceph/nodeset/ceph_secret.yaml
  dt/osasinfra/edpm-post-ceph/nodeset/extra_mounts.yaml
  dt/osasinfra/edpm-post-ceph/nodeset/kustomization.yaml
  dt/osasinfra/edpm-pre-ceph/deployment/kustomization.yaml
  dt/osasinfra/edpm-pre-ceph/nodeset/kustomization.yaml
  dt/osasinfra/kustomization.yaml
  dt/osasinfra/namespace.yaml
  dt/osasinfra/nncp/kustomization.yaml
  dt/osasinfra/ocp_networks_octavia_netattach.yaml
  examples/dt/osasinfra/.gitignore
  examples/dt/osasinfra/README.md
  examples/dt/osasinfra/control-plane.md
  examples/dt/osasinfra/control-plane/.gitignore
  examples/dt/osasinfra/control-plane/kustomization.yaml
  examples/dt/osasinfra/control-plane/nncp/.gitignore
  examples/dt/osasinfra/control-plane/nncp/kustomization.yaml
  examples/dt/osasinfra/control-plane/nncp/values.yaml
  examples/dt/osasinfra/control-plane/service-values.yaml
  examples/dt/osasinfra/dataplane-post-ceph.md
  examples/dt/osasinfra/dataplane-pre-ceph.md
  examples/dt/osasinfra/deployment/kustomization.yaml
  examples/dt/osasinfra/deployment/values.yaml
  examples/dt/osasinfra/edpm-pre-ceph/.gitignore
  examples/dt/osasinfra/edpm-pre-ceph/deployment/kustomization.yaml
  examples/dt/osasinfra/edpm-pre-ceph/deployment/values.yaml
  examples/dt/osasinfra/edpm-pre-ceph/nodeset/kustomization.yaml
  examples/dt/osasinfra/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/osasinfra/kustomization.yaml
  examples/dt/osasinfra/service-values.yaml
  examples/dt/osasinfra/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: deployment-topology, ready-review, ready-merge, approved, lgtm, ok-to-test

#308 Add tainted worker to unibeta
  automation/net-env/uni02beta.yaml
  examples/dt/uni02beta/control-plane/nncp/kustomization.yaml
  examples/dt/uni02beta/control-plane/nncp/nodes.yaml
  examples/dt/uni02beta/control-plane/nncp/values.yaml
Labels: approved, lgtm, needs-downstream-testing

#309 Don't use symlinks for automation/net-env/
  automation/net-env/uni01alpha.yaml
  automation/net-env/uni04delta.yaml
  automation/net-env/uni05epsilon.yaml
  automation/net-env/uni06zeta.yaml
  automation/net-env/uni07eta.yaml
Labels: approved, lgtm

#322 [BGP] Install conntrack on EDPM nodes
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#321 Fix indent in VA1 example doc
  examples/va/hci/dataplane-post-ceph.md
Labels: approved, lgtm

#318 [BGP] Set edpm_ovn_encap_ip value to bgpmainnet_ip
  automation/vars/bgp.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#324 OSASINFRA: Adjust timeouts to match va-hci ones
  automation/vars/osasinfra.yaml
  examples/dt/osasinfra/control-plane.md
  examples/dt/osasinfra/dataplane-post-ceph.md
  examples/dt/osasinfra/dataplane-pre-ceph.md
Labels: approved, lgtm, ok-to-test

#211 Add ironic config to uni01alpha
  dt/uni01alpha/kustomization.yaml
  dt/uni01alpha/nad.yaml
  dt/uni01alpha/netconfig/kustomization.yaml
  dt/uni01alpha/netconfig/netconfig.yaml
  dt/uni01alpha/nncp/kustomization.yaml
  examples/dt/uni01alpha/README.md
  examples/dt/uni01alpha/control-plane/nncp/values.yaml
  examples/dt/uni01alpha/control-plane/service-values.yaml
  lib/nncp/ocp_node_template.yaml
Labels: deployment-topology, testing-complete, approved, lgtm

#319 Uni04delta ipv6
  automation/mocks/uni04delta-ipv6.yaml
  automation/net-env/uni04delta-ipv6.yaml
  automation/vars/uni04delta-ipv6.yaml
  dt/uni04delta-ipv6/README.md
  dt/uni04delta-ipv6/edpm-pre-ceph/deployment/kustomization.yaml
  dt/uni04delta-ipv6/edpm-pre-ceph/nodeset/kustomization.yaml
  dt/uni04delta-ipv6/edpm/deployment/kustomization.yaml
  dt/uni04delta-ipv6/edpm/nodeset/ceph_secret.yaml
  dt/uni04delta-ipv6/edpm/nodeset/extra_mounts.yaml
  dt/uni04delta-ipv6/edpm/nodeset/kustomization.yaml
  dt/uni04delta-ipv6/edpm/nodeset/nova_ceph.yaml
  dt/uni04delta-ipv6/kustomization.yaml
  dt/uni04delta-ipv6/nad.yaml
  dt/uni04delta-ipv6/namespace.yaml
  dt/uni04delta-ipv6/nncp/kustomization.yaml
  examples/dt/uni04delta-ipv6/.gitignore
  examples/dt/uni04delta-ipv6/README.md
  examples/dt/uni04delta-ipv6/control-plane.md
  examples/dt/uni04delta-ipv6/control-plane/.gitignore
  examples/dt/uni04delta-ipv6/control-plane/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/.gitignore
  examples/dt/uni04delta-ipv6/control-plane/nncp/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/nncp/values.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
  examples/dt/uni04delta-ipv6/deployment/kustomization.yaml
  examples/dt/uni04delta-ipv6/deployment/values.yaml
  examples/dt/uni04delta-ipv6/edpm-pre-ceph.md
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/.gitignore
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/kustomization.yaml
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/nodeset/.gitignore
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/nodeset/kustomization.yaml
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/values.yaml
  examples/dt/uni04delta-ipv6/edpm.md
  examples/dt/uni04delta-ipv6/kustomization.yaml
  examples/dt/uni04delta-ipv6/values.yaml
  lib/nncp_ipv6/kustomization.yaml
  lib/nncp_ipv6/ocp_node_template.yaml
  lib/nncp_ipv6/ocp_nodes_nncp.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#327 Fix missing octavia-ca-passphrase secret
  dt/uni06zeta/kustomization.yaml
Labels: approved, lgtm

#333 [Uni Eta] Set mtu same as Uni Zeta
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#332 uni-delta: really enable cinder-backup
  dt/uni04delta-ipv6/edpm/nodeset/kustomization.yaml
  dt/uni04delta/edpm/nodeset/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
Labels: needs-testing, approved, lgtm

#330 Re-enable cinder multipath in glance
  dt/uni05epsilon/edpm/nodeset/nova_custom.yaml
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: testing-complete, approved, lgtm

#331 Allow to customize operators subscription channel
  examples/common/olm/values.yaml
  lib/olm-openstack/kustomization.yaml
Labels: testing-complete, lgtm

#334 Do not quote ctlplane_dns_nameservers list in delta-ipv6
  examples/dt/uni04delta-ipv6/values.yaml
Labels: approved, lgtm

#241 Add missing next hop route to octavia network attachment
  examples/dt/bgp/control-plane/nncp/values.yaml
  examples/dt/uni01alpha/control-plane/nncp/values.yaml
Labels: needs-testing, approved, lgtm

#337 Revert "Revert "Re enable ovn_emit_need_to_frag""
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#340 [nfv] Bump controlplane timeout
  automation/vars/default.yaml
Labels: approved, lgtm

#317 Enable heat for in uni02beta DT
  dt/uni02beta/kustomization.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
Labels: testing-complete, approved, lgtm, ok-to-test

#341 Revert "Disable Horizon service temporarily"
  dt/uni04delta-ipv6/kustomization.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
Labels: needs-testing, approved, lgtm, needs-downstream-testing

#272 explictly define nova cell templated instead of relying on defaulting
  lib/control-plane/openstackcontrolplane.yaml
Labels: testing-complete, approved, lgtm

#344 [uni02beta] Reenable file/NFS for glance
  dt/uni02beta/kustomization.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
Labels: testing-complete, approved, lgtm

#343 [uni06zeta] Add missing networking and service values
  dt/uni06zeta/kustomization.yaml
  dt/uni06zeta/nncp/kustomization.yaml
  dt/uni06zeta/resources/octavia-network-attachment-definition.yaml
  dt/uni06zeta/resources/octavia-network-attachment-defintion.yaml
  examples/dt/uni06zeta/README.md
  examples/dt/uni06zeta/control-plane/nncp/kustomization.yaml
  examples/dt/uni06zeta/control-plane/nncp/values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
Labels: approved, lgtm

#347 Add ovn-encap-tos inherit to delta-ipv6
  examples/dt/uni04delta-ipv6/values.yaml
Labels: needs-testing, approved, lgtm, ok-to-test

#350 Add ovn-encap-tos inherit to delta-ipv6
  examples/dt/uni04delta-ipv6/values.yaml
Labels: approved, lgtm

#349 Disable extra mount in uni02beta
  dt/uni02beta/kustomization.yaml
Labels: approved, lgtm, ok-to-test
