Repository openstack-k8s-operators/architecture, pull requests merged in 2024-08, with the labels that each got.

#353 Deploy 2 replicas of DNS per default
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#357 Use pre/post Ceph servicesOverride in HCI deployments
  examples/va/hci/dataplane-post-ceph.md
  examples/va/hci/deployment/kustomization.yaml
  examples/va/hci/deployment/values.yaml
  examples/va/hci/edpm-pre-ceph/deployment/kustomization.yaml
  examples/va/hci/edpm-pre-ceph/deployment/values.yaml
  examples/va/hci/edpm-pre-ceph/nodeset/values.yaml
  examples/va/hci/values.yaml
Labels: approved, lgtm, needs-18.0.0-proposed-cherry-pick

#360 Use pre/post Ceph servicesOverride in HCI deployments
  examples/va/hci/dataplane-post-ceph.md
  examples/va/hci/deployment/kustomization.yaml
  examples/va/hci/deployment/values.yaml
  examples/va/hci/edpm-pre-ceph/deployment/kustomization.yaml
  examples/va/hci/edpm-pre-ceph/deployment/values.yaml
  examples/va/hci/edpm-pre-ceph/nodeset/values.yaml
  examples/va/hci/values.yaml
Labels: approved, lgtm

#362 convert pidone va to dt
  README.md
  automation/vars/pidone.yaml
  dt/pidone/README.md
  dt/pidone/edpm/deployment/kustomization.yaml
  dt/pidone/edpm/nodeset/kustomization.yaml
  dt/pidone/kustomization.yaml
  dt/pidone/namespace.yaml
  examples/dt/pidone/README.md
  examples/dt/pidone/edpm/deployment/kustomization.yaml
  examples/dt/pidone/edpm/deployment/values.yaml
  examples/dt/pidone/edpm/nodeset/kustomization.yaml
  examples/dt/pidone/edpm/nodeset/values.yaml
  examples/dt/pidone/kustomization.yaml
  examples/dt/pidone/nncp/kustomization.yaml
  examples/dt/pidone/nncp/ocp_pidone_nodes_nncp.yaml
  examples/dt/pidone/nncp/values.yaml
  examples/dt/pidone/service-values.yaml
  examples/dt/pidone/values.yaml
  va/pidone/README.md
  zuul.d/validations.yaml
Labels: approved, lgtm

#365 increased NFV timeout
  automation/vars/default.yaml
Labels: approved, lgtm

#355 Enable ironic on delta-ipv6
  dt/uni04delta-ipv6/kustomization.yaml
Labels: approved, lgtm

#363 Changing ntp to ci-framework default
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/values.yaml
  examples/dt/bgp/edpm/nodeset/values.yaml
  examples/dt/osasinfra/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/pidone/edpm/nodeset/values.yaml
  examples/dt/pidone/values.yaml
  examples/dt/uni01alpha/edpm/values.yaml
  examples/dt/uni01alpha/networker/nodeset/values.yaml
  examples/dt/uni02beta/values.yaml
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni04delta-ipv6/values.yaml
  examples/dt/uni04delta/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni04delta/values.yaml
  examples/dt/uni05epsilon/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni06zeta/values.yaml
  examples/dt/uni07eta/edpm/values.yaml
  examples/dt/uni07eta/networker/nodeset/values.yaml
  examples/va/hci/edpm-pre-ceph/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-sriov/edpm/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk/edpm/nodeset/values.yaml
  examples/va/nfv/sriov/edpm/nodeset/values.yaml
Labels: approved, lgtm

#358 Use pre/post Ceph servicesOverride in uni05epsilon HCI
  examples/dt/uni05epsilon/dataplane-post-ceph.md
  examples/dt/uni05epsilon/deployment/kustomization.yaml
  examples/dt/uni05epsilon/deployment/values.yaml
  examples/dt/uni05epsilon/edpm-pre-ceph/deployment/kustomization.yaml
  examples/dt/uni05epsilon/edpm-pre-ceph/deployment/values.yaml
  examples/dt/uni05epsilon/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni05epsilon/values.yaml
Labels: testing-complete, approved, lgtm

#316 HCI+NFV architecture
  automation/vars/default.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/README.md
  dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph/namespace.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph/policy.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/deployment/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/ceph_secret.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/extra_mounts.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/nova_ovs_dpdk_sriov_ceph.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/baremetalset-password-secret.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/neutron_igmp.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/nova_ovs_dpdk_sriov.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/README.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/nncp/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/nncp/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/service-values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/dataplane-post-ceph.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/dataplane-pre-ceph.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/deployment/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/service-values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: ready-merge, approved, lgtm, ok-to-test, needs-18.0.0-proposed-cherry-pick

#369 HCI+NFV DT
  automation/vars/default.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/README.md
  dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph/namespace.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane-pre-ceph/policy.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/deployment/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/ceph_secret.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/extra_mounts.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-post-ceph/nodeset/nova_ovs_dpdk_sriov_ceph.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/baremetalset-password-secret.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/kustomization.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/neutron_igmp.yaml
  dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/nova_ovs_dpdk_sriov.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/README.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/nncp/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/nncp/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/control-plane/service-values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/dataplane-post-ceph.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/dataplane-pre-ceph.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/deployment/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/service-values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#370 [BGP] Use 'nova' service instead of 'nova-custom'
  dt/bgp/edpm/nodeset/kustomization.yaml
  dt/bgp/edpm/nodeset/nova_custom.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#372 [BGP] Use 'nova' service instead of 'nova-custom'
  dt/bgp/edpm/nodeset/kustomization.yaml
  dt/bgp/edpm/nodeset/nova_custom.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
Labels: approved, lgtm

#380 Enable debug option in manila
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/va/hci/service-values.yaml
Labels: approved, lgtm, needs-18.0.0-proposed-cherry-pick

#381 Enable debug option in manila
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/va/hci/service-values.yaml
Labels: approved, lgtm

#375 Move automation default vars into seperate scenario files
  automation/vars/hci.yaml
  automation/vars/nfv-ovs-dpdk-sriov-hci.yaml
  automation/vars/ovs-dpdk-sriov.yaml
  automation/vars/ovs-dpdk.yaml
  automation/vars/sriov.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm
