Repository openstack-k8s-operators/architecture, pull requests merged in 2024-04, with the labels that each got.

#204 [va-hci] Remove references to edpm images
  examples/va/hci/edpm-pre-ceph/nodeset/values.yaml
Labels: bugfix, triaged

#208 Drop nncp ctlplane routes
  examples/dt/uni01alpha/control-plane/nncp/values.yaml
  examples/dt/uni06zeta/control-plane/nncp/values.yaml
  examples/va/hci/control-plane/nncp/values.yaml
  examples/va/nfv/ovs-dpdk-sriov/nncp/values.yaml
  examples/va/nfv/ovs-dpdk/nncp/values.yaml
  examples/va/nfv/sriov/nncp/values.yaml
  lib/nncp/kustomization.yaml
  lib/nncp/ocp_node_template.yaml
Labels: bugfix, ready-merge

#207 Provide documentation for pull request testing
  docs/contributing/pull-request-testing.md
  mkdocs.yml
Labels: documentation, testing, triaged
