Repository openstack-k8s-operators/architecture, pull requests merged in 2024-09, with the labels that each got.

#384 Move bgp_dt01 into its own automation file
  automation/vars/bgp.yaml
  automation/vars/bgp_dt01.yaml
Labels: approved, lgtm, do-not-merge/hold

#383 Drop default.yaml file
  automation/vars/default.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#379 Ensure we have one scenario per automation file
  .ci/automation-schema.yaml
  .ci/validate-schema-paths.py
Labels: approved, lgtm

#388 Add 'local' network type in the Control Plane CRs
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#374 Enable Downstream trigger job in the architecture repo
  create-zuul-jobs.py
  zuul.d/projects.yaml
  zuul.d/trigger-jobs.yaml
Labels: approved, lgtm

#373 NFV-HCI minor fixes
  automation/mocks/nfv-ovs-dpdk-sriov-hci.yaml
  automation/vars/nfv-ovs-dpdk-sriov-hci.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/deployment/values.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#389 Add 'local' network type in the Control Plane CRs
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni04delta-ipv6/control-plane/service-values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#335 Enable Octavia in Uni01alpha
  examples/dt/uni01alpha/control-plane/service-values.yaml
Labels: approved, lgtm

#391 [delta-ipv6] Shared control plane vars
  dt/uni04delta-ipv6/control-plane/kustomization.yaml
  dt/uni04delta-ipv6/edpm/nodeset/kustomization.yaml
  dt/uni04delta-ipv6/kustomization.yaml
Labels: approved, lgtm

#395 [Uni02Beta] Install conntrack on EDPM nodes
  examples/dt/uni02beta/values.yaml
Labels: testing-complete, ready-review, approved, lgtm, needs-18.0.0-proposed-cherry-pick

#397 Merge pull request Enable Octavia in uni01alpha and uni07eta jobs
  dt/uni07eta/kustomization.yaml
  examples/dt/uni01alpha/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/nncp/values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#399 Document using openshift-cherrypick-robot
  docs/contributing/cherry-picking.md
Labels: approved, lgtm

#409 Add swift interface to pidone dt
  dt/pidone/kustomization.yaml
  examples/dt/pidone/nncp/values.yaml
Labels: testing-complete, approved, lgtm
