Repository openstack-k8s-operators/architecture, pull requests merged in 2024-12, with the labels that each got.

#444 Switch to 1500 MTU consistently
  examples/dt/uni01alpha/control-plane/nncp/values.yaml
  examples/dt/uni02beta/control-plane/nncp/values.yaml
  examples/dt/uni06zeta/control-plane/nncp/values.yaml
  examples/dt/uni07eta/control-plane/nncp/values.yaml
Labels: approved, lgtm, ok-to-test

#451 Add automation file for uni-alpha-adoption.
  automation/net-env/uni01alpha-adoption.yaml
  automation/vars/uni01alpha-adoption.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#461 Merge pull request #458 from gmarcian/add_conntrack_tools
  examples/dt/uni04delta-ipv6/values.yaml
Labels: approved, lgtm, ok-to-test

#459 Set Cinder customServiceConfig globally in DCN DT
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#356 Revert "Disable extra mount in uni02beta"
  dt/uni02beta/kustomization.yaml
Labels: testing-complete, approved, lgtm

#460 [DCN DT] Set table-id explicitly for routes
  examples/dt/dcn/control-plane/nncp/values.yaml
Labels: approved, lgtm

#466 [BGP] Replace worker-3 NAD from host-device to macvlan
  examples/dt/bgp/bgp_dt01/control-plane/nncp/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/nncp/values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#431 Add telemetry metricStorage for NFV
  examples/va/nfv/ovs-dpdk-sriov/service-values.yaml
  va/nfv/ovs-dpdk-sriov/kustomization.yaml
Labels: ready-review, approved, lgtm

#469 Multiple nodesets for ovs-dpdk-sriov scenario (reuse edpm-nodeset-values)
  automation/vars/ovs-dpdk-sriov-2nodesets.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/README.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/control-plane.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/dataplane.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/deployment/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/nodeset/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/nodeset/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/nodeset2/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/nodeset2/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/nncp/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/nncp/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/service-values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm
