Repository openstack-k8s-operators/architecture, pull requests merged in 2024-05, with the labels that each got.

#193 BGP basic configurations
  automation/vars/bgp.yaml
  dt/bgp/edpm/deployment/kustomization.yaml
  dt/bgp/edpm/nodeset/kustomization.yaml
  dt/bgp/edpm/nodeset/nova_custom.yaml
  dt/bgp/kustomization.yaml
  dt/bgp/namespace.yaml
  dt/bgp/networking/bgpmetallb/kustomization.yaml
  dt/bgp/networking/bgpmetallb/metallb_bgpadvertisements.yaml
  dt/bgp/networking/bgpmetallb/metallb_bgppeers.yaml
  dt/bgp/networking/nad/kustomization.yaml
  dt/bgp/networking/nad/ocp_network_template.yaml
  dt/bgp/networking/nad/ocp_networks_netattach.yaml
  dt/bgp/ocp_networks_octavia_netattach.yaml
  examples/dt/bgp/README.md
  examples/dt/bgp/control-plane.md
  examples/dt/bgp/control-plane/kustomization.yaml
  examples/dt/bgp/control-plane/nncp/.gitignore
  examples/dt/bgp/control-plane/nncp/kustomization.yaml
  examples/dt/bgp/control-plane/nncp/values.yaml
  examples/dt/bgp/control-plane/service-values.yaml
  examples/dt/bgp/dataplane.md
  examples/dt/bgp/edpm/deployment/kustomization.yaml
  examples/dt/bgp/edpm/deployment/values.yaml
  examples/dt/bgp/edpm/nodeset/kustomization.yaml
  examples/dt/bgp/edpm/nodeset/values.yaml
Labels: deployment-topology, triaged

#205 Revert "[dt/uni01alpha] Enable octavia services"
  examples/dt/uni01alpha/control-plane/service-values.yaml
Labels: deployment-topology, needs-testing, needs-info

#145 CRs for unified beta deployed topology
  automation/vars/uni02beta.yaml
  dt/uni02beta/README.md
  dt/uni02beta/cinder-netapp-secrets.yaml
  dt/uni02beta/edpm/kustomization.yaml
  dt/uni02beta/kustomization.yaml
  dt/uni02beta/manila-netapp-secrets.yaml
  dt/uni02beta/namespace.yaml
  examples/dt/uni02beta/.gitignore
  examples/dt/uni02beta/README.md
  examples/dt/uni02beta/control-plane.md
  examples/dt/uni02beta/control-plane/.gitignore
  examples/dt/uni02beta/control-plane/kustomization.yaml
  examples/dt/uni02beta/control-plane/nncp/.gitignore
  examples/dt/uni02beta/control-plane/nncp/kustomization.yaml
  examples/dt/uni02beta/control-plane/nncp/values.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
  examples/dt/uni02beta/data-plane.md
  examples/dt/uni02beta/kustomization.yaml
  examples/dt/uni02beta/values.yaml
Labels: deployment-topology, ↟ priority-high

#225 Fix the spec path for the amphora and apache images for octavia
  dt/bgp/kustomization.yaml
  dt/uni01alpha/kustomization.yaml
Labels: bugfix, deployment-topology, needs-info

#222 Add barbican
  lib/control-plane/openstackcontrolplane.yaml
Labels: deployment-topology, validated-architecture, ready-review

#236 Revert "Revert "Added github-gate pipeline""
  zuul.d/projects.yaml
Labels: approved, lgtm

#229 Fix octavia network attachment subnet range.
  examples/dt/bgp/control-plane/nncp/values.yaml
  examples/dt/uni01alpha/README.md
  examples/dt/uni01alpha/control-plane/nncp/values.yaml
Labels: testing-complete, approved

#230 Start adding validation jobs
  automation/mocks/ovs-dpdk-sriov.yaml
  zuul.d/projects.yaml
  zuul.d/validate-jobs.yaml
Labels: automation, testing, ready-review, ↟ priority-high, approved, lgtm

#191 Uni delta
  automation/vars/uni04delta.yaml
  dt/uni04delta/README.md
  dt/uni04delta/edpm-pre-ceph/deployment/kustomization.yaml
  dt/uni04delta/edpm-pre-ceph/nodeset/kustomization.yaml
  dt/uni04delta/edpm/deployment/kustomization.yaml
  dt/uni04delta/edpm/nodeset/ceph_secret.yaml
  dt/uni04delta/edpm/nodeset/extra_mounts.yaml
  dt/uni04delta/edpm/nodeset/kustomization.yaml
  dt/uni04delta/edpm/nodeset/nova_ceph.yaml
  dt/uni04delta/kustomization.yaml
  dt/uni04delta/namespace.yaml
  examples/dt/uni04delta/.gitignore
  examples/dt/uni04delta/README.md
  examples/dt/uni04delta/control-plane.md
  examples/dt/uni04delta/control-plane/.gitignore
  examples/dt/uni04delta/control-plane/kustomization.yaml
  examples/dt/uni04delta/control-plane/nncp/.gitignore
  examples/dt/uni04delta/control-plane/nncp/kustomization.yaml
  examples/dt/uni04delta/control-plane/nncp/values.yaml
  examples/dt/uni04delta/control-plane/service-values.yaml
  examples/dt/uni04delta/deployment/kustomization.yaml
  examples/dt/uni04delta/deployment/values.yaml
  examples/dt/uni04delta/edpm-pre-ceph.md
  examples/dt/uni04delta/edpm-pre-ceph/.gitignore
  examples/dt/uni04delta/edpm-pre-ceph/kustomization.yaml
  examples/dt/uni04delta/edpm-pre-ceph/nodeset/.gitignore
  examples/dt/uni04delta/edpm-pre-ceph/nodeset/kustomization.yaml
  examples/dt/uni04delta/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni04delta/edpm-pre-ceph/values.yaml
  examples/dt/uni04delta/edpm.md
  examples/dt/uni04delta/kustomization.yaml
  examples/dt/uni04delta/values.yaml
Labels: deployment-topology, ↟ priority-high, approved, lgtm

#243 Add karelyatin to reviewers list
  OWNERS
Labels: approved, lgtm

#239 Set Cinder API and Backup replicas to 3 for HCI VA
  examples/va/hci/service-values.yaml
  va/hci/edpm-post-ceph/nodeset/kustomization.yaml
Labels: validated-architecture, testing-complete, triaged, approved, lgtm

#232 Generate build jobs for all automations
  .github/workflows/linter.yaml
  .yamllint.yml
  automation/mocks/ovs-dpdk.yaml
  automation/mocks/sriov.yaml
  automation/vars/README.md
  create-zuul-jobs.py
  zuul.d/base-jobs.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#246 Set edpmRoleServiceName for nova-custom-ceph
  va/hci/edpm-post-ceph/nodeset/nova_ceph.yaml
Labels: ↟ priority-high, approved, lgtm

#247 Add edpmServiceType to nova_ceph.yaml
  va/hci/edpm-post-ceph/nodeset/nova_ceph.yaml
Labels: approved, lgtm

#155 [uni-epsilon] Provide deployment topology
  automation/vars/uni05epsilon.yaml
  dt/uni05epsilon/README.md
  dt/uni05epsilon/edpm/deployment/kustomization.yaml
  dt/uni05epsilon/edpm/nodeset/kustomization.yaml
  dt/uni05epsilon/kustomization.yaml
  dt/uni05epsilon/namespace.yaml
  dt/uni05epsilon/nncp/kustomization.yaml
  dt/uni05epsilon/resources/cinder-volume-nfs-secrets.yaml
  dt/uni05epsilon/resources/cinder-volume-ontap-secrets.yaml
  dt/uni05epsilon/resources/octavia-network-attachment-definition.yaml
  examples/dt/uni05epsilon/README.md
  examples/dt/uni05epsilon/control-plane.md
  examples/dt/uni05epsilon/control-plane/kustomization.yaml
  examples/dt/uni05epsilon/control-plane/nncp/kustomization.yaml
  examples/dt/uni05epsilon/control-plane/nncp/values.yaml
  examples/dt/uni05epsilon/control-plane/service-values.yaml
  examples/dt/uni05epsilon/data-plane.md
  examples/dt/uni05epsilon/deployment/kustomization.yaml
  examples/dt/uni05epsilon/deployment/values.yaml
  examples/dt/uni05epsilon/kustomization.yaml
  examples/dt/uni05epsilon/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: deployment-topology, ↟ priority-high, approved, lgtm

#245 Add PIDONE VA (ipv4)
  README.md
  automation/vars/pidone.yaml
  examples/va/pidone/README.md
  examples/va/pidone/edpm/deployment/kustomization.yaml
  examples/va/pidone/edpm/deployment/values.yaml
  examples/va/pidone/edpm/nodeset/kustomization.yaml
  examples/va/pidone/edpm/nodeset/values.yaml
  examples/va/pidone/kustomization.yaml
  examples/va/pidone/nncp/kustomization.yaml
  examples/va/pidone/nncp/ocp_pidone_nodes_nncp.yaml
  examples/va/pidone/nncp/values.yaml
  examples/va/pidone/service-values.yaml
  examples/va/pidone/values.yaml
  va/pidone/README.md
  va/pidone/edpm/deployment/kustomization.yaml
  va/pidone/edpm/nodeset/kustomization.yaml
  va/pidone/kustomization.yaml
  va/pidone/namespace.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: validated-architecture, ↟ priority-high, approved, lgtm

#256 Use BGP specific Net Env Def in CI
  automation/mocks/bgp.yaml
  automation/mocks/pidone.yaml
  zuul.d/validations.yaml
Labels: bugfix, ↟ priority-high, approved, lgtm

#255 Set default config options for all Cinder services
  lib/control-plane/openstackcontrolplane.yaml
Labels: ready-merge, approved, lgtm

#253 Add missing barbican service overrides
  lib/control-plane/kustomization.yaml
Labels: ↟ priority-high, approved, lgtm

#249 Add edpmServiceType to nova_ceph.yaml
  dt/uni04delta/edpm/nodeset/nova_ceph.yaml
Labels: approved, lgtm, ok-to-test

#250 Remove unused params from OpenStackDataPlaneNodeSet examples
  examples/dt/bgp/edpm/nodeset/values.yaml
  examples/dt/uni01alpha/edpm/values.yaml
  examples/dt/uni01alpha/networker/nodeset/values.yaml
  examples/dt/uni02beta/values.yaml
  examples/dt/uni04delta/values.yaml
  examples/dt/uni05epsilon/values.yaml
  examples/dt/uni06zeta/values.yaml
  examples/va/hci/edpm-pre-ceph/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-sriov/edpm/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk/edpm/nodeset/values.yaml
  examples/va/nfv/sriov/edpm/nodeset/values.yaml
Labels: approved, lgtm

#237 Add bgp_dt01 Deployed Topology
  automation/mocks/bgp_dt01.yaml
  automation/vars/bgp.yaml
  examples/dt/bgp/bgp_dt01/README.md
  examples/dt/bgp/bgp_dt01/configure-taints.md
  examples/dt/bgp/bgp_dt01/control-plane.md
  examples/dt/bgp/bgp_dt01/control-plane/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/metallb_bgppeers.yaml
  examples/dt/bgp/bgp_dt01/control-plane/nncp/.gitignore
  examples/dt/bgp/bgp_dt01/control-plane/nncp/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/nncp/ocp_worker_nodes_nncp.yaml
  examples/dt/bgp/bgp_dt01/control-plane/nncp/values.yaml
  examples/dt/bgp/bgp_dt01/control-plane/ocp_network_template.yaml
  examples/dt/bgp/bgp_dt01/control-plane/ocp_networks_netattach.yaml
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
  examples/dt/bgp/bgp_dt01/data-plane.md
  examples/dt/bgp/bgp_dt01/edpm/computes-deployment/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes-deployment/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers-deployment/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers-deployment/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/values.yaml
  examples/dt/bgp/bgp_dt01/metallb/README.md
  examples/dt/bgp/bgp_dt01/metallb/kustomization.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: deployment-topology, ready-review, ↟ priority-high, approved, lgtm
