Repository openstack-k8s-operators/architecture, pull requests merged in 2025-08, with the labels that each got.

#589 Increase glance haproxy+httpd timeout (for large images)
  lib/control-plane/openstackcontrolplane.yaml
Labels: approved, lgtm

#503 Octavia DCN support
  automation/net-env/dcn.yaml
  dt/dcn/control-plane/kustomization.yaml
  dt/dcn/kustomization.yaml
  dt/dcn/nad.yaml
  dt/dcn/nncp/kustomization.yaml
  examples/dt/dcn/README.md
  examples/dt/dcn/control-plane/nncp/kustomization.yaml
  examples/dt/dcn/control-plane/nncp/values.yaml
  examples/dt/dcn/control-plane/scaledown/service-values.yaml
  examples/dt/dcn/dataplane-post-ceph.md
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm, do-not-merge/hold

#601 Update jinja2 template to work with ansible 2.19
  examples/dt/bgp-l3-xl/edpm/computes/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r2/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r2/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r2/values.yaml
  examples/dt/bmo01/dataplane/nodesets/values.yaml
  examples/dt/dcn/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/nodeset/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-2nodesets/edpm/nodeset2/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-hci/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/computes/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/networkers/values.yaml
  examples/dt/nova/nova-three-cells/edpm/nodeset/values.yaml
  examples/dt/nova/nova-three-cells/edpm/nodeset2/values.yaml
  examples/dt/nova/nova01alpha/edpm/nodeset/values.yaml
  examples/dt/osasinfra-ipv6/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/osasinfra/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/pidone/edpm/nodeset/values.yaml
  examples/dt/pidone/values.yaml
  examples/dt/uni01alpha/edpm/values.yaml
  examples/dt/uni01alpha/networker/nodeset/values.yaml
  examples/dt/uni02beta/values.yaml
  examples/dt/uni04delta-ipv6/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni04delta-ipv6/values.yaml
  examples/dt/uni04delta/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni04delta/values.yaml
  examples/dt/uni05epsilon/edpm-pre-ceph/nodeset/values.yaml
  examples/dt/uni05epsilon/nodeset2/edpm-pre-ceph/values.yaml
  examples/dt/uni06zeta/values.yaml
  examples/dt/uni07eta/edpm/values.yaml
  examples/dt/uni07eta/networker/nodeset/values.yaml
  examples/va/hci/edpm-pre-ceph/nodeset/values.yaml
  examples/va/multi-namespace/edpm/nodeset/values.yaml
  examples/va/multi-namespace/edpm2/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-networker/edpm/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-networker/networker/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-sriov/edpm/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk/edpm/nodeset/values.yaml
  examples/va/nfv/sriov/edpm/nodeset/values.yaml
  examples/va/nvidia-mdev/edpm/nodeset/values.yaml
Labels: approved, lgtm

#600 [OSPRH-19024] Remove bridged ctlplane network from multi-ns VA
  examples/va/multi-namespace/control-plane/kustomization.yaml
  examples/va/multi-namespace/control-plane/networking/kustomization.yaml
  examples/va/multi-namespace/control-plane/networking/nncp/kustomization.yaml
  examples/va/multi-namespace/control-plane/networking/nncp/values.yaml
  examples/va/multi-namespace/control-plane2/kustomization.yaml
  examples/va/multi-namespace/control-plane2/networking/nncp/values.yaml
  va/multi-namespace/control-plane2/networking/kustomization.yaml
  va/multi-namespace/control-plane2/networking/nncp/kustomization.yaml
Labels: testing-complete, approved, lgtm

#607 Remove .swp file left over from vi
  examples/dt/bgp-l3-xl/control-plane/networking/nncp/.values.yaml.swp
Labels: approved, lgtm

#606 Introduce Distributed Zone with 3rd Party Storage DT
  automation/mocks/dz-storage.yaml
  automation/vars/dz-storage.yaml
  examples/dt/dz-storage/README.md
  examples/dt/dz-storage/bgp-configuration.md
  examples/dt/dz-storage/configure-taints.md
  examples/dt/dz-storage/control-plane.md
  examples/dt/dz-storage/control-plane/cinder-volume-secrets-az0.yaml
  examples/dt/dz-storage/control-plane/cinder-volume-secrets-az1.yaml
  examples/dt/dz-storage/control-plane/cinder-volume-secrets-az2.yaml
  examples/dt/dz-storage/control-plane/kustomization.yaml
  examples/dt/dz-storage/control-plane/manila-share-secrets-az0.yaml
  examples/dt/dz-storage/control-plane/manila-share-secrets-az1.yaml
  examples/dt/dz-storage/control-plane/manila-share-secrets-az2.yaml
  examples/dt/dz-storage/control-plane/networking/kustomization.yaml
  examples/dt/dz-storage/control-plane/networking/metallb_bgppeers.yaml
  examples/dt/dz-storage/control-plane/networking/nncp/.gitignore
  examples/dt/dz-storage/control-plane/networking/nncp/kustomization.yaml
  examples/dt/dz-storage/control-plane/networking/nncp/ocp_worker_nodes_nncp.yaml
  examples/dt/dz-storage/control-plane/networking/nncp/values.yaml
  examples/dt/dz-storage/control-plane/networking/ocp_network_template.yaml
  examples/dt/dz-storage/control-plane/networking/ocp_networks_netattach.yaml
  examples/dt/dz-storage/control-plane/service-values.yaml
  examples/dt/dz-storage/control-plane/tuned
  examples/dt/dz-storage/data-plane.md
  examples/dt/dz-storage/disable-rp-filters.md
  examples/dt/dz-storage/edpm/computes/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/nova-extra-config.yaml
  examples/dt/dz-storage/edpm/computes/r0/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/r0/values.yaml
  examples/dt/dz-storage/edpm/computes/r1/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/r1/values.yaml
  examples/dt/dz-storage/edpm/computes/r2/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/r2/values.yaml
  examples/dt/dz-storage/edpm/deployment/kustomization.yaml
  examples/dt/dz-storage/edpm/deployment/values.yaml
  examples/dt/dz-storage/edpm/networkers/r0/kustomization.yaml
  examples/dt/dz-storage/edpm/networkers/r0/values.yaml
  examples/dt/dz-storage/edpm/networkers/r1/kustomization.yaml
  examples/dt/dz-storage/edpm/networkers/r1/values.yaml
  examples/dt/dz-storage/edpm/networkers/r2/kustomization.yaml
  examples/dt/dz-storage/edpm/networkers/r2/values.yaml
  examples/dt/dz-storage/metallb/README.md
  examples/dt/dz-storage/metallb/kustomization.yaml
  examples/dt/dz-storage/topology/README.md
  examples/dt/dz-storage/topology/azone-node-affinity.yaml
  examples/dt/dz-storage/topology/bzone-node-affinity.yaml
  examples/dt/dz-storage/topology/czone-node-affinity.yaml
  examples/dt/dz-storage/topology/default-spread-pods.yaml
  examples/dt/dz-storage/topology/kustomization.yaml
  examples/dt/dz-storage/topology/node-zone-labels.yaml
  examples/dt/dz-storage/validate.md
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: ready-review, approved
