Repository openstack-k8s-operators/architecture, pull requests merged in 2025-06, with the labels that each got.

#554 Added Cinder Backup in kustomization for uni02beta
  dt/uni02beta/kustomization.yaml
  examples/dt/uni02beta/control-plane/service-values.yaml
Labels: approved, lgtm, ok-to-test

#555 Adding telemetry bits to uni-gamma
  examples/va/hci/deployment/values.yaml
  examples/va/hci/service-values.yaml
  examples/va/hci/values.yaml
  va/hci/edpm-post-ceph/nodeset/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#566 [BGP] Set edpm_network_config_nmstate=false
  examples/dt/bgp-l3-xl/edpm/computes/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r2/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r2/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r2/values.yaml
Labels: approved, lgtm

#567 Add WatcherPassword to osp-secrets
  lib/control-plane/osp-secrets.env
Labels: approved, lgtm

#572 Decouple BGP network stage from control plane stage
  automation/vars/bgp-l3-xl.yaml
  automation/vars/bgp_dt01.yaml
  dt/bgp/kustomization.yaml
  dt/bgp/namespace.yaml
  dt/bgp/networking/kustomization.yaml
  dt/bgp/networking/ocp_networks_octavia_netattach.yaml
  examples/dt/bgp-l3-xl/control-plane.md
  examples/dt/bgp-l3-xl/control-plane/kustomization.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/kustomization.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/metallb_bgppeers.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/nncp/.gitignore
  examples/dt/bgp-l3-xl/control-plane/networking/nncp/.values.yaml.swp
  examples/dt/bgp-l3-xl/control-plane/networking/nncp/kustomization.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/nncp/ocp_worker_nodes_nncp.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/nncp/values.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/ocp_network_template.yaml
  examples/dt/bgp-l3-xl/control-plane/networking/ocp_networks_netattach.yaml
  examples/dt/bgp_dt01/control-plane.md
  examples/dt/bgp_dt01/control-plane/kustomization.yaml
  examples/dt/bgp_dt01/control-plane/networking/kustomization.yaml
  examples/dt/bgp_dt01/control-plane/networking/metallb_bgppeers.yaml
  examples/dt/bgp_dt01/control-plane/networking/nncp/.gitignore
  examples/dt/bgp_dt01/control-plane/networking/nncp/kustomization.yaml
  examples/dt/bgp_dt01/control-plane/networking/nncp/ocp_worker_nodes_nncp.yaml
  examples/dt/bgp_dt01/control-plane/networking/nncp/values.yaml
  examples/dt/bgp_dt01/control-plane/networking/ocp_network_template.yaml
  examples/dt/bgp_dt01/control-plane/networking/ocp_networks_netattach.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#573 Remove unnecessary rootwrap_config
  examples/dt/uni05epsilon/service-values.yaml
  examples/dt/uni06zeta/control-plane/service-values.yaml
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: approved, lgtm

#575 [hci] Make the timeout for edpm post ceph deployment longer
  automation/vars/hci.yaml
Labels: lgtm
