Repository openstack-k8s-operators/architecture, pull requests merged in 2025-02, with the labels that each got.

#495 Remove reference to deleted downstream workflow
  .github/workflows/trigger-downstream-gh-action-job.yaml
Labels: approved, lgtm

#462 Add scaling down a DCN site
  dt/dcn/control-plane/kustomization.yaml
  dt/dcn/edpm-post-ceph/nodeset/kustomization.yaml
  examples/dt/dcn/control-plane/scaledown/kustomization.yaml
  examples/dt/dcn/control-plane/scaledown/service-values.yaml
  examples/dt/dcn/dataplane-post-ceph.md
Labels: approved, lgtm

#481 Switch cinder uniquePodNames to true for DCN deployments
  dt/dcn/control-plane/kustomization.yaml
  examples/dt/dcn/control-plane/scaledown/service-values.yaml
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#484 BGP controlplane Pure L3 Spine&Leaf
  automation/mocks/bgp_dt01.yaml
  automation/vars/bgp_dt01.yaml
  dt/bgp/edpm/nodeset/kustomization.yaml
  examples/dt/bgp/bgp_dt01/README.md
  examples/dt/bgp/bgp_dt01/bgp-configuration.md
  examples/dt/bgp/bgp_dt01/control-plane/nncp/kustomization.yaml
  examples/dt/bgp/bgp_dt01/control-plane/nncp/values.yaml
  examples/dt/bgp/bgp_dt01/control-plane/service-values.yaml
  examples/dt/bgp/bgp_dt01/data-plane.md
  examples/dt/bgp/bgp_dt01/disable-rp-filters.md
  examples/dt/bgp/bgp_dt01/edpm/computes/r0/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/r1/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/r2/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/deployment/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/r0/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/r1/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/r2/kustomization.yaml
  examples/dt/bgp/bgp_dt01/edpm/networkers/r2/values.yaml
  lib/nncp-l3/kustomization.yaml
  lib/nncp-l3/ocp_node_template.yaml
  lib/nncp-l3/ocp_nodes_nncp.yaml
  zuul.d/validations.yaml
Labels: testing-complete, ready-review

#489 Decouple VA1 network stage from control plane stage
  automation/vars/hci-adoption.yaml
  automation/vars/hci.yaml
  examples/va/hci/control-plane.md
  examples/va/hci/control-plane/kustomization.yaml
  examples/va/hci/control-plane/networking/kustomization.yaml
  examples/va/hci/control-plane/networking/nncp/.gitignore
  examples/va/hci/control-plane/networking/nncp/kustomization.yaml
  examples/va/hci/control-plane/networking/nncp/values.yaml
  examples/va/hci/kustomization.yaml
  va/hci/kustomization.yaml
  va/hci/networking/kustomization.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#467 [DCN] Support Manila Shares with Local Ceph Clusters in DCN
  dt/dcn/control-plane/kustomization.yaml
  examples/dt/dcn/control-plane/scaledown/service-values.yaml
  examples/dt/dcn/service-values.yaml
Labels: approved, lgtm

#508 Update COO sub channel to stable
  examples/dt/uni01alpha/control-plane.md
  lib/olm-deps/coo_subscription.yaml
Labels: approved, lgtm

#510 [BGP_DT01] edpm_frr_bgp_uplinks removed from EDPM CRs
  examples/dt/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r2/values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#512 [BGP] Fix EDPM hostnames
  examples/dt/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r2/values.yaml
Labels: approved, lgtm

#493 NFV EDPM OVS DPDK with Netoworker OVS DPDK
  examples/va/nfv/ovs-dpdk-networker/.gitignore
  examples/va/nfv/ovs-dpdk-networker/README.md
  examples/va/nfv/ovs-dpdk-networker/control-plane.md
  examples/va/nfv/ovs-dpdk-networker/dataplane.md
  examples/va/nfv/ovs-dpdk-networker/edpm/.gitignore
  examples/va/nfv/ovs-dpdk-networker/edpm/deployment/.gitignore
  examples/va/nfv/ovs-dpdk-networker/edpm/deployment/kustomization.yaml
  examples/va/nfv/ovs-dpdk-networker/edpm/deployment/values.yaml
  examples/va/nfv/ovs-dpdk-networker/edpm/nodeset/.gitignore
  examples/va/nfv/ovs-dpdk-networker/edpm/nodeset/kustomization.yaml
  examples/va/nfv/ovs-dpdk-networker/edpm/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-networker/kustomization.yaml
  examples/va/nfv/ovs-dpdk-networker/networker/.gitignore
  examples/va/nfv/ovs-dpdk-networker/networker/nodeset/.gitignore
  examples/va/nfv/ovs-dpdk-networker/networker/nodeset/kustomization.yaml
  examples/va/nfv/ovs-dpdk-networker/networker/nodeset/values.yaml
  examples/va/nfv/ovs-dpdk-networker/nncp/kustomization.yaml
  examples/va/nfv/ovs-dpdk-networker/nncp/values.yaml
  examples/va/nfv/ovs-dpdk-networker/service-values.yaml
  lib/dataplane/networker-nodeset/dataplane-ssh-secret.yaml
  lib/dataplane/networker-nodeset/kustomization.yaml
  lib/dataplane/networker-nodeset/openstackdataplanenodeset.yaml
  va/nfv/ovs-dpdk-networker/README.md
  va/nfv/ovs-dpdk-networker/edpm/deployment/kustomization.yaml
  va/nfv/ovs-dpdk-networker/edpm/nodeset/baremetalset-password-secret.yaml
  va/nfv/ovs-dpdk-networker/edpm/nodeset/kustomization.yaml
  va/nfv/ovs-dpdk-networker/edpm/nodeset/nova_ovs_dpdk.yaml
  va/nfv/ovs-dpdk-networker/kustomization.yaml
  va/nfv/ovs-dpdk-networker/namespace.yaml
  va/nfv/ovs-dpdk-networker/networker/nodeset/baremetalset-password-secret.yaml
  va/nfv/ovs-dpdk-networker/networker/nodeset/kustomization.yaml
Labels: approved, lgtm
