Repository openstack-k8s-operators/architecture, pull requests merged in 2025-04, with the labels that each got.

#533 Add bgp-l3-xl dt
  automation/mocks/bgp-l3-xl.yaml
  automation/vars/bgp-l3-xl.yaml
  dt/bgp/kustomization.yaml
  examples/dt/bgp-l3-xl/README.md
  examples/dt/bgp-l3-xl/bgp-configuration.md
  examples/dt/bgp-l3-xl/configure-taints.md
  examples/dt/bgp-l3-xl/control-plane.md
  examples/dt/bgp-l3-xl/control-plane/kustomization.yaml
  examples/dt/bgp-l3-xl/control-plane/metallb_bgppeers.yaml
  examples/dt/bgp-l3-xl/control-plane/nncp/.gitignore
  examples/dt/bgp-l3-xl/control-plane/nncp/kustomization.yaml
  examples/dt/bgp-l3-xl/control-plane/nncp/ocp_worker_nodes_nncp.yaml
  examples/dt/bgp-l3-xl/control-plane/nncp/values.yaml
  examples/dt/bgp-l3-xl/control-plane/ocp_network_template.yaml
  examples/dt/bgp-l3-xl/control-plane/ocp_networks_netattach.yaml
  examples/dt/bgp-l3-xl/control-plane/service-values.yaml
  examples/dt/bgp-l3-xl/control-plane/tuned
  examples/dt/bgp-l3-xl/data-plane.md
  examples/dt/bgp-l3-xl/disable-rp-filters.md
  examples/dt/bgp-l3-xl/edpm/computes/r0/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r1/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r2/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r2/values.yaml
  examples/dt/bgp-l3-xl/edpm/deployment/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/deployment/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r0/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r1/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r2/kustomization.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r2/values.yaml
  examples/dt/bgp-l3-xl/metallb/README.md
  examples/dt/bgp-l3-xl/metallb/kustomization.yaml
  lib/nncp-l3/ocp_node_template.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#543 Add names to BGP automation steps
  automation/vars/bgp-l3-xl.yaml
  automation/vars/bgp_dt01.yaml
Labels: testing-complete, approved, lgtm

#537 Add OpenStack OLM subscription configurations
  examples/common/olm-subscriptions/README.md
  examples/common/olm-subscriptions/kustomization.yaml
  examples/common/olm-subscriptions/values.yaml
  lib/olm-openstack-subscriptions/base/catalogsource.yaml
  lib/olm-openstack-subscriptions/base/kustomization.yaml
  lib/olm-openstack-subscriptions/base/namespaces.yaml
  lib/olm-openstack-subscriptions/base/operatorgroup.yaml
  lib/olm-openstack-subscriptions/overlays/default/kustomization.yaml
  lib/olm-openstack-subscriptions/overlays/default/openstack-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/barbican-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/cinder-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/designate-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/glance-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/heat-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/horizon-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/infra-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/ironic-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/keystone-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/kustomization.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/manila-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/mariadb-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/neutron-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/nova-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/octavia-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/openstack-ansibleee-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/openstack-baremetal-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/openstack-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/ovn-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/placement-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/rabbitmq-cluster-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/swift-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.3/telemetry-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/barbican-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/cinder-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/designate-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/glance-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/heat-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/horizon-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/infra-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/ironic-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/keystone-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/kustomization.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/manila-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/mariadb-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/neutron-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/nova-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/octavia-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/openstack-baremetal-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/openstack-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/ovn-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/placement-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/rabbitmq-cluster-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/swift-subscription.yaml
  lib/olm-openstack-subscriptions/overlays/v1.0.6/telemetry-subscription.yaml
Labels: approved, lgtm

#540 [BGP] Remove ctlplane from NNCP
  examples/dt/bgp-l3-xl/control-plane/nncp/kustomization.yaml
  examples/dt/bgp_dt01/control-plane/nncp/kustomization.yaml
  lib/nncp-l3/kustomization.yaml
  lib/nncp-l3/ocp_node_template.yaml
Labels: testing-complete, ready-review, ready-merge, approved, lgtm

#482 [NFV] Deploy Networker in ovs-dpdk-sriov scenario
  automation/mocks/ovs-dpdk-sriov-networker.yaml
  automation/vars/ovs-dpdk-sriov-networker.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/README.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/control-plane.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/dataplane.md
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/computes/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/computes/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/computes/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/deployment/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/deployment/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/deployment/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/networkers/.gitignore
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/networkers/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/edpm/networkers/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/nncp/kustomization.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/nncp/values.yaml
  examples/dt/nfv/nfv-ovs-dpdk-sriov-networker/service-values.yaml
  examples/va/nfv/ovs-dpdk-networker/networker/nodeset/kustomization.yaml
  lib/dataplane/compute-nodeset
  va/nfv/ovs-dpdk-sriov/edpm/compute-nodeset
  va/nfv/ovs-dpdk-sriov/edpm/networker-nodeset/baremetalset-password-secret.yaml
  va/nfv/ovs-dpdk-sriov/edpm/networker-nodeset/kustomization.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: ready-review, approved

#546 Fix typo about worker-3 in bgp-l3-xl
  examples/dt/bgp-l3-xl/README.md
Labels: approved, lgtm
