Repository openstack-k8s-operators/architecture, pull requests merged in 2025-09, with the labels that each got.

#611 Add SNR/NHC to dz-storage DT
  automation/vars/dz-storage.yaml
  examples/dt/dz-storage/README.md
Labels: approved, lgtm

#613 Update Glance configuration for dz-storage
  automation/vars/dz-storage.yaml
  examples/dt/dz-storage/control-plane/kustomization.yaml
  examples/dt/dz-storage/control-plane/service-values.yaml
  examples/dt/dz-storage/data-plane.md
  examples/dt/dz-storage/edpm/computes/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/nova-extra-config.yaml
  examples/dt/dz-storage/edpm/computes/r0/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/r0/nova-custom-az0.yaml
  examples/dt/dz-storage/edpm/computes/r0/nova-extra-config-az0.yaml
  examples/dt/dz-storage/edpm/computes/r0/values.yaml
  examples/dt/dz-storage/edpm/computes/r1/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/r1/nova-custom-az1.yaml
  examples/dt/dz-storage/edpm/computes/r1/nova-extra-config-az1.yaml
  examples/dt/dz-storage/edpm/computes/r1/values.yaml
  examples/dt/dz-storage/edpm/computes/r2/kustomization.yaml
  examples/dt/dz-storage/edpm/computes/r2/nova-custom-az2.yaml
  examples/dt/dz-storage/edpm/computes/r2/nova-extra-config-az2.yaml
  examples/dt/dz-storage/edpm/computes/r2/values.yaml
Labels: approved, lgtm

#615 Remove references to downstream-* trigger jobs
  create-zuul-jobs.py
  zuul.d/projects.yaml
  zuul.d/trigger-jobs.yaml
Labels: approved, lgtm

#610 Add some missing Kustomize APIVersion and Kind fields
  examples/common/metallb/kustomization.yaml
  examples/common/nmstate/kustomization.yaml
  examples/common/olm-subscriptions/kustomization.yaml
  examples/common/olm/kustomization.yaml
  examples/common/openstack/kustomization.yaml
  examples/dt/bgp-l3-xl/metallb/kustomization.yaml
  examples/dt/bgp_dt01/metallb/kustomization.yaml
Labels: approved, lgtm

#614 Add ovn-encap-tos inherit to uni04delta-ipv4 and uni07eta
  examples/dt/uni04delta/values.yaml
  examples/dt/uni07eta/values.yaml
Labels: approved, lgtm, ok-to-test

#605 New uni09iota DT
  automation/net-env/uni09iota.yaml
  automation/vars/uni09iota.yaml
  dt/uni09iota/README.md
  dt/uni09iota/cinder-volume-pure-fc-secrets.yaml
  dt/uni09iota/edpm/kustomization.yaml
  dt/uni09iota/kustomization.yaml
  dt/uni09iota/namespace.yaml
  dt/uni09iota/networking/kustomization.yaml
  examples/dt/uni09iota/README.md
  examples/dt/uni09iota/control-plane.md
  examples/dt/uni09iota/control-plane/kustomization.yaml
  examples/dt/uni09iota/control-plane/networking/kustomization.yaml
  examples/dt/uni09iota/control-plane/networking/nncp/kustomization.yaml
  examples/dt/uni09iota/control-plane/networking/nncp/values.yaml
  examples/dt/uni09iota/control-plane/service-values.yaml
  examples/dt/uni09iota/data-plane.md
  examples/dt/uni09iota/kustomization.yaml
  examples/dt/uni09iota/values.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: ready-review, approved, lgtm

#619 [BGP] Remove ovnController
  examples/dt/bgp-l3-xl/control-plane/kustomization.yaml
  examples/dt/bgp-l3-xl/control-plane/service-values.yaml
  examples/dt/bgp_dt01/control-plane/kustomization.yaml
  examples/dt/bgp_dt01/control-plane/service-values.yaml
  examples/dt/bgp_dt04_ipv6/control-plane/kustomization.yaml
  examples/dt/bgp_dt04_ipv6/control-plane/service-values.yaml
  examples/dt/dz-storage/control-plane/kustomization.yaml
  examples/dt/dz-storage/control-plane/service-values.yaml
Labels: testing-complete, ready-review, approved, lgtm

#596 Increase glance and cinder timeouts (haproxy+httpd (and RPC))
  lib/control-plane/base/openstackcontrolplane.yaml
Labels: approved, lgtm
