Repository openstack-k8s-operators/architecture, pull requests merged in 2025-05, with the labels that each got.

#455 Va nvidia mdev
  automation/vars/nvidia-mdev.yaml
  examples/va/nvidia-mdev/.gitignore
  examples/va/nvidia-mdev/README.md
  examples/va/nvidia-mdev/control-plane.md
  examples/va/nvidia-mdev/control-plane/.gitignore
  examples/va/nvidia-mdev/control-plane/kustomization.yaml
  examples/va/nvidia-mdev/control-plane/nncp/.gitignore
  examples/va/nvidia-mdev/control-plane/nncp/kustomization.yaml
  examples/va/nvidia-mdev/control-plane/nncp/values.yaml
  examples/va/nvidia-mdev/control-plane/service-values.yaml
  examples/va/nvidia-mdev/edpm-post-driver/.gitignore
  examples/va/nvidia-mdev/edpm-post-driver/deployment/.gitignore
  examples/va/nvidia-mdev/edpm-post-driver/deployment/kustomization.yaml
  examples/va/nvidia-mdev/edpm-post-driver/deployment/values.yaml
  examples/va/nvidia-mdev/edpm-post-driver/nodeset/.gitignore
  examples/va/nvidia-mdev/edpm-post-driver/nodeset/kustomization.yaml
  examples/va/nvidia-mdev/edpm-post-driver/nodeset/values.yaml
  examples/va/nvidia-mdev/edpm-post.md
  examples/va/nvidia-mdev/edpm-pre.md
  examples/va/nvidia-mdev/edpm/.gitignore
  examples/va/nvidia-mdev/edpm/deployment/.gitignore
  examples/va/nvidia-mdev/edpm/deployment/kustomization.yaml
  examples/va/nvidia-mdev/edpm/deployment/values.yaml
  examples/va/nvidia-mdev/edpm/nodeset/.gitignore
  examples/va/nvidia-mdev/edpm/nodeset/kustomization.yaml
  examples/va/nvidia-mdev/edpm/nodeset/values.yaml
  va/nvidia-mdev/edpm-post-driver/deployment/kustomization.yaml
  va/nvidia-mdev/edpm-post-driver/nodeset/kustomization.yaml
  va/nvidia-mdev/edpm-post-driver/nodeset/nova_provider.yaml
  va/nvidia-mdev/edpm/deployment/kustomization.yaml
  va/nvidia-mdev/edpm/nodeset/baremetalset-password-secret.yaml
  va/nvidia-mdev/edpm/nodeset/kustomization.yaml
  va/nvidia-mdev/edpm/nodeset/nova_sriov.yaml
  va/nvidia-mdev/kustomization.yaml
  va/nvidia-mdev/namespace.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: testing-complete, ready-review, approved, lgtm

#549 Update external unideltaipv6
  automation/net-env/uni04delta-ipv6-adoption.yaml
  automation/net-env/uni04delta-ipv6.yaml
Labels: approved, lgtm

#547 [OSPRH-15434] Multi-namespace VA
  automation/net-env/multi-namespace.yaml
  automation/vars/multi-namespace.yaml
  examples/va/multi-namespace/.gitignore
  examples/va/multi-namespace/README.md
  examples/va/multi-namespace/control-plane.md
  examples/va/multi-namespace/control-plane/.gitignore
  examples/va/multi-namespace/control-plane/kustomization.yaml
  examples/va/multi-namespace/control-plane/networking/kustomization.yaml
  examples/va/multi-namespace/control-plane/networking/nncp/.gitignore
  examples/va/multi-namespace/control-plane/networking/nncp/kustomization.yaml
  examples/va/multi-namespace/control-plane/networking/nncp/values.yaml
  examples/va/multi-namespace/control-plane/service-values.yaml
  examples/va/multi-namespace/control-plane2/.gitignore
  examples/va/multi-namespace/control-plane2/kustomization.yaml
  examples/va/multi-namespace/control-plane2/networking/kustomization.yaml
  examples/va/multi-namespace/control-plane2/networking/nncp/kustomization.yaml
  examples/va/multi-namespace/control-plane2/networking/nncp/values.yaml
  examples/va/multi-namespace/control-plane2/service-values.yaml
  examples/va/multi-namespace/dataplane.md
  examples/va/multi-namespace/edpm/.gitignore
  examples/va/multi-namespace/edpm/kustomization.yaml
  examples/va/multi-namespace/edpm/nodeset/kustomization.yaml
  examples/va/multi-namespace/edpm/nodeset/values.yaml
  examples/va/multi-namespace/edpm/values.yaml
  examples/va/multi-namespace/edpm2/.gitignore
  examples/va/multi-namespace/edpm2/kustomization.yaml
  examples/va/multi-namespace/edpm2/nodeset/kustomization.yaml
  examples/va/multi-namespace/edpm2/nodeset/values.yaml
  examples/va/multi-namespace/edpm2/values.yaml
  examples/va/multi-namespace/namespace.md
  examples/va/multi-namespace/namespace/.gitignore
  examples/va/multi-namespace/namespace/kustomization.yaml
  examples/va/multi-namespace/namespace/values.yaml
  va/multi-namespace/control-plane2/networking/kustomization.yaml
  va/multi-namespace/control-plane2/networking/nncp/kustomization.yaml
  va/multi-namespace/edpm2/kustomization.yaml
  va/multi-namespace/edpm2/nodeset/kustomization.yaml
  va/multi-namespace/namespace/kustomization.yaml
  va/multi-namespace/namespace/namespace.yaml
  zuul.d/projects.yaml
  zuul.d/validations.yaml
Labels: approved, lgtm

#553 Adds workflow to trigger branch sync
  .github/workflows/sync_branches_with_ext_trigger.yml
Labels: approved, lgtm

#562 [BGP][EDPM] Postpone validate-network after frr
  examples/dt/bgp-l3-xl/edpm/computes/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/computes/r2/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r0/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r1/values.yaml
  examples/dt/bgp-l3-xl/edpm/networkers/r2/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r2/values.yaml
Labels: testing-complete, ready-review, ready-merge, approved, lgtm
