Repository openstack-k8s-operators/architecture, pull requests merged in 2025-03, with the labels that each got.

#500 Update NFV VAs to use network vanity names
  examples/va/nfv/ovs-dpdk-sriov/nncp/values.yaml
  examples/va/nfv/ovs-dpdk/nncp/values.yaml
  examples/va/nfv/sriov/nncp/values.yaml
Labels: approved, lgtm

#479 Enable nested SNAT in uni-eta
  examples/dt/uni07eta/control-plane/service-values.yaml
Labels: ok-to-test

#518 fix broken link in nfv ovs-dpdk doc
  examples/va/nfv/ovs-dpdk/dataplane.md
Labels: approved, lgtm, ok-to-test

#513 Increase timeout in uni01alpha
  automation/vars/uni01alpha.yaml
Labels: approved, lgtm

#519 Added name param for stages to get named stages in automation/vars for all unijobs
  .ci/automation-schema.yaml
  automation/vars/hci-adoption.yaml
  automation/vars/hci.yaml
  automation/vars/uni01alpha-adoption.yaml
  automation/vars/uni01alpha.yaml
  automation/vars/uni02beta.yaml
  automation/vars/uni04delta-adoption.yaml
  automation/vars/uni04delta-ipv6.yaml
  automation/vars/uni04delta.yaml
  automation/vars/uni05epsilon-adoption.yaml
  automation/vars/uni05epsilon.yaml
  automation/vars/uni06zeta-adoption.yaml
  automation/vars/uni06zeta.yaml
  automation/vars/uni07eta.yaml
Labels: ready-merge, approved, lgtm, ok-to-test

#522 [BGP] Remove L2Advertisements
  examples/dt/bgp_dt01/control-plane/kustomization.yaml
Labels: testing-complete, ready-review, approved, lgtm

#525 external netwrok list missing for networker ovs dpdk
  examples/va/nfv/ovs-dpdk-networker/networker/nodeset/values.yaml
Labels: approved, lgtm

#526 Revert "[BGP] Disable BFD"
  examples/dt/bgp_dt01/edpm/computes/r0/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r1/values.yaml
  examples/dt/bgp_dt01/edpm/computes/r2/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r0/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r1/values.yaml
  examples/dt/bgp_dt01/edpm/networkers/r2/values.yaml
Labels: testing-complete, ready-review, approved, lgtm
